### PR TITLE
DRAFT: Add 2D interactor and image readers

### LINKED ISSUE #49: Consider adding a 2D interactor
If an image is 2D, it can be useful to have a 2D interactor (I'm thinking of DXF or medical images).
And tbh, if we implement it, then it makes sense to supports JPG/PNG/TIFF/HDR/TGA/... too since it is basically free.
I know this is not the main purpose of f3d but since f3d is GPU accelerated, it may outperform other image previewers with large images.

### PR DESCRIPTION
**Pull request by jpouderoux**
Fixes #49 

- [x] Add 2D interactor
- [x] Allow to switch between 2D and 3D interactors with `2` and `3` keys
- [x] Set the 2D interactor automatically for 2D data
- [x] Disable lighthing for 2D image data
- [ ] Set image scalars visibility by default for 2D image data
- [ ] Tests

### CODE REVIEW

**Comment by mwestphal** [comment]
> Allow to switch between 2D and 3D interactors with 2 and 3 keys

There is already a hotkey to switch between interactors, why not cycle through available interactors ?

**Comment by jpouderoux** [comment]
> > Allow to switch between 2D and 3D interactors with 2 and 3 keys
> 
> There is already a hotkey to switch between interactors, why not cycle through available interactors ?

Which key are you thinking about? `K` ?

**Comment by mwestphal** [comment]
> > > Allow to switch between 2D and 3D interactors with 2 and 3 keys
> > 
> > 
> > There is already a hotkey to switch between interactors, why not cycle through available interactors ?
> 
> Which key are you thinking about? `K` ?

yes

**Comment by jpouderoux** [comment]
> > > > Allow to switch between 2D and 3D interactors with 2 and 3 keys
> > > 
> > > 
> > > There is already a hotkey to switch between interactors, why not cycle through available interactors ?
> > 
> > 
> > Which key are you thinking about? `K` ?
> 
> yes

`K` enables trackball in 3D mode, looks a bit different to me and mixing the 2 concepts looks a bit confusing to me, don't you think?

**Comment by mwestphal** [comment]
maybe we should discuss a bit about the right way to integrate this. There a few possibilities imo.

**Comment by mwestphal** [comment]
> `K` enables trackball in 3D mode, looks a bit different to me and mixing the 2 concepts looks a bit confusing to me, don't you think?

Thinking about it, I agree

**Pull request closed without merging**
