### PR TITLE
Detect incorrect implicit values usage

### PR DESCRIPTION
**Pull request by mwestphal**
- All options without an implicit value now error out if used with an implicit value
- Add a F3DExFailure exception
 - Fix incorrect return code when using incorrect options

### CODE REVIEW

**Comment by snoyer** [comment]
That will catch a bunch of stuff at a syntactic level (eg. `--config` should be an error and this PR makes it one) :+1:
But for #1103 there's still a problem at the semantics level (`--config=` and `--config=""` are syntactically valid but nonsensical and should probably generate a warning)

**Comment by mwestphal** [comment]
if a user specify `--config=""` let them specify it. I dont see a problem with that.

It let user keep the default behavior of F3D while still specifying a `--config`. I can imagine a scenario where this is valid.

One could argue that if a user can set `--config= ` involontarly, then they will probably be able to set `--config=""` involontaly as well, but I cant detect it since it is a correct value imo.

**Comment by snoyer** [comment]
The app should be able to generate a warning when it receives an empty string where it expects a filename (and right now it doesn't because it uses an empty string to represent a not-set optional value).
It's not actually in the scope for this PR (it only mentions #1103 but doesn't claim to fix it, my bad) so it doesn't really matter here. 

---

back on the topic of this PR there might be a slight drawback to this whole argparse hackery:
```F3D - A fast and minimalist 3D viewer
Usage:
  bin/f3d [OPTIONS...] file1 file2 ...

 Applicative options:
      --input [=<files>(=f3d_application_reserved)]
                                Input files
      --output [=<png file>(=f3d_application_reserved)]
                                Render to file
      --no-background           No background when render to file
  -h, --help                    Print help
      --version                 Print version details
      --readers-list            Print the list of readers
      --config [=<filePath/filename/fileStem>(=f3d_application_reserved)]
                                Specify the configuration file to use. 
                                absolute/relative path or filename/filestem 
                                to search in configuration file locations.
      --dry-run                 Do not read the configuration file
      --no-render               Do not render anything and quit right after 
                                loading the first file, use with --verbose 
                                to recover information about a file.
      --max-size [=<size in Mib>(=f3d_application_reserved)]
                                Maximum size in Mib of a file to load, 
                                negative value means unlimited (default: 
                                -1)
      --load-plugins [=<paths or names>(=f3d_application_reserved)]
                                List of plugins to load separated with a 
                                comma
...
```
that's a lot of `f3d_application_reserved` leaking out through the help text :/ unfortunately there may not be an easy way to fix it without refactoring the whole `DeclareOption` mechanism :(

**Comment by mwestphal** [comment]
Indeed, dropping this. Cannot be implemented like this anyway.

**Pull request closed without merging**
