### PR TITLE
Fix colormap documentation

### PR DESCRIPTION
**Pull request by Meakk**
Existing page: https://f3d.app/doc/user/COLOR_MAPS.html
Fixed page: https://meakk.github.io/f3d/doc/user/COLOR_MAPS.html

### CODE REVIEW

**Review by mwestphal — COMMENTED** [review]
I wonder if you need to keep the sizes for the markdown rendering?

https://github.com/f3d-app/f3d/blob/master/doc/user/COLOR_MAPS.md

**Comment by Meakk** [comment]
> I wonder if you need to keep the sizes for the markdown rendering?
> 
> https://github.com/f3d-app/f3d/blob/master/doc/user/COLOR_MAPS.md

Still readable imho: https://github.com/meakk/f3d/blob/master/doc/user/COLOR_MAPS.md

**Comment by mwestphal** [comment]
Why not have both though ?

**Comment by Meakk** [comment]
> Why not have both though ?

done

**Review by mwestphal — APPROVED** [review]

**Pull request merged**
