### PR TITLE
Updating VTK for #341

### PR DESCRIPTION
**Pull request by mwestphal**
Updating VTK for #341

### CODE REVIEW

**Comment by Meakk** [comment]
Don't you need to increment the build number to take it into consideration?

**Comment by mwestphal** [comment]
Nope, the sha is part of the cache key. Incrementing the build number is only necessary when changing a CMake options.

**Comment by mwestphal** [comment]
> 72/211 Test  #68: f3d::TestTextureColorWithOptions ................................   Passed    1.01 sec

**Comment by mwestphal** [comment]
all windows tests are segfaulting @Meakk Ill rerun, if it fails again i can try on windows locally.

**Comment by Meakk** [comment]
This is weird. I hope it's not a regression in VTK.

**Comment by mwestphal** [comment]
Unable to reprodue locally

**Comment by mwestphal** [comment]
building an older commit works, most likely a regression. Ill bisect it on the CI but this is going to take a while.

**Comment by mwestphal** [comment]
Regression caused by https://gitlab.kitware.com/vtk/vtk/-/merge_requests/9386

**Comment by mwestphal** [comment]
Still unable to reproduce on windows, the output window works great.

**Comment by mwestphal** [comment]
Some informations:

- Crash is caused by our early call to  win->SetDisplayMode during initialisation.
- Im able to reproduce by using F3D_WINDOWS_GUI and building in Release mode.
- Without this call, we do not have any outputs (according to CI, testing in progress)

**Comment by mwestphal** [comment]
@Meakk No idea why the new version of the output window broke our init but I implemented a much cleaner/better version which works perfectly. please review.

**Review by Meakk — APPROVED** [review]

**Pull request merged**
