### PR TITLE
fix clipping when setting camera position via arguments/options

### PR DESCRIPTION
**Pull request by schuhumi**
as per https://github.com/f3d-app/f3d/issues/108#issuecomment-993001731

Fix issue #108

### CODE REVIEW

**Comment by Meakk** [comment]
Thanks! Is it fixing your issue?

**Comment by schuhumi** [comment]
Yes, it is fixing it! Sorry I wrote that in issue 108 only

**Comment by Meakk** [comment]
We'll need a test to ensure no regression, don't worry it's very simple with f3d, please see `cmake/testing.cmake`.  
- Add a line in `cmake/testing.cmake`, probably something like `f3d_test(NAME TestCameraClipping DATA erythrocyte2_.obj ARGS --camera-position=0,0,39 --camera-focal-point=0,0,0 --camera-view-up=1,0,0 --camera-view-angle=20)`  
- Copy `erythrocyte2_.obj` and `erythrocyte2_.mtl` to `data/testing` folder.
- Copy the expected resulting image in `data/baselines/TestCameraClipping.png`

If you do not want or are not allowed to include your data, please use any existing data in `data/testing` folder.

**Comment by Meakk** [comment]
@schuhumi you can add `RESOLUTION 800,600` in your `f3d_test` declaration and remove it from the config file.

**Comment by schuhumi** [comment]
@Meakk Ohh okay, is there a way to run test locally too? I'm not proficient with cmake and didn't understand how those work yet

**Comment by Meakk** [comment]
Yes, you can test it locally. Just enable testing with CMake (`BUILD_TESTING` variable enabled with `ccmake` or `cmake-gui`), then build your project again. You can then run the test using `ctest -R TestCameraClipping`.

**Comment by Meakk** [comment]
@schuhumi looks good. Let me know if we can merge it.

**Comment by schuhumi** [comment]
Finally seems to work as intended. For documentation sake this is the object I created to make the issue more obvious, a checkerboard with green border:
TestCameraClipping
This is what it looks like when it gets clipped:
TestCameraClipping_fail

The clipping depends on both the camera settings and the size of the object, but I tried to make it prone to fail in case of clipping error:
- extend into depth from camera's point of view
- have the whole object visible, not the back covered by non-translucent front or something)

**Review by Meakk — APPROVED** [review]

**Comment by Meakk** [comment]
Thanks @schuhumi !

**Comment by mwestphal** [comment]
a license line should be added for the new file

**Comment by Meakk** [comment]
> a license line should be added for the new data file

I'll take care of it.

**Comment by schuhumi** [comment]
Oh I see, thank you for taking care of it. I created the data file solely for this test myself, so no strings attached.

**Comment by mwestphal** [comment]
Thanks a lot for your contribution @schuhumi !

**Comment by mwestphal** [comment]
@Meakk : file have not been uploaded as lfs for some reason, looking into it.

**Comment by mwestphal** [comment]
https://github.com/f3d-app/f3d/pull/167

@schuhumi : you may have a git lfs issue, let us know if you need help with that.

**Comment by schuhumi** [comment]
@mwestphal Oh I'm very sorry. I am familiar with lfs, but it didn't occur to me that it was used in the data folder. Since I was running my own test only and did't miss lfs data for that, no error made me aware of that. Actually I didn't even have lfs on my host installed, because the other projects I use it in are dockerized development environments.

In retrospect, considering how much q&a + work I caused you two with such a simple contribution, it might be worthwhile to write down a couple hints for non-regular contributors. I very much like how clean and organized the project is, this is not a source of confusion. It's just unfamiliar tooling, and the small things you overlook when trying to navigate a foreign code base. 

In the README.md at the "Build" section could be a good place to mention that git lfs is required for the data folder. After the "Configuration and building" subsection a short explanation how to run tests would have been helpful for me at least.

**Comment by mwestphal** [comment]
@schuhumi : You are most definitely right. We are planning to rework the documentation and add a CONTRIBUTING.md that will cover all of this. README.md is getting way too long at this point.

**Pull request merged**
