### PR TITLE
Add Alembic in CI

### PR DESCRIPTION
**Pull request by Meakk**
Preparing CI for https://github.com/f3d-app/f3d/pull/179

### CODE REVIEW

**Comment by Meakk** [comment]
@nyue taking care of building Alembic in this PR. It's still a WIP. I'll let you know when it's done.

**Comment by Meakk** [comment]
Ok, it was easy! Can you take a look @mwestphal?  
@nyue I'm building Imath 3.1.3 and Alembic 1.8.3, is it fine?

**Comment by nyue** [comment]
> Ok, it was easy! Can you take a look @mwestphal? @nyue I'm building Imath 3.1.3 and Alembic 1.8.3, is it fine?

Yes, I have tested Imath 3.1.3 and Alembic 1.8.3 locally on my Ubuntu Box.

**Comment by mwestphal** [comment]
update third party licenses.md

**Review by mwestphal — CHANGES_REQUESTED** [review]
update third party licenses

**Comment by Meakk** [comment]
> update third party licenses

@nyue is adding it in his PR. I don't think it is necessary for this particular PR because I'm only building it.

**Comment by mwestphal** [comment]
> > update third party licenses
> 
> @nyue is adding it in his PR. I don't think it is necessary for this particular PR because I'm only building it.

Indeed, not necessary until static link with f3d is present.

**Review by mwestphal — APPROVED** [review]

**Pull request merged**
