### PR TITLE
Fix a clang format issue

### PR DESCRIPTION
**Pull request by mwestphal**

### CODE REVIEW

**Comment by Meakk** [comment]
Why isn't it detected by the CI?

**Comment by mwestphal** [comment]
Version of clang format I suppose ? What does your clang format says ?

**Comment by Meakk** [comment]
> Version of clang format I suppose ? What does your clang format says ?

Nothing. Are you sure you don't have an additional rule locally? Anyway, I approve the PR.

**Review by Meakk — APPROVED** [review]

**Comment by mwestphal** [comment]
the new version is the one I would expect with our rules anyway, unless the file is being excluded somewhere for some reasons ?

**Pull request merged**
